# Server port
server.port=8082

# PostgreSQL DB (Render)
spring.datasource.url=postgresql://fms_b44z_user:I2dHhCDJaaMJNE3uJyOo5V4Iy58aelfa@dpg-d78n9mgule4c73a7e5jg-a.singapore-postgres.render.com/fms_b44z
spring.datasource.username=fms_b44z_user
spring.datasource.password=I2dHhCDJaaMJNE3uJyOo5V4Iy58aelfa
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

